### PR TITLE
Zilliqa pre audit updates

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by junhaoyap — COMMENTED** [review]
Mostly looks good, one remaining question and something I've noticed is that ZRC2 standardises the usage of `amount` and we seem to be mixing `value` and `amount` across the contracts, we should standardise this too?

**Review by ChiuWeiYi — APPROVED** [review]
no comments from my side,
double-checked transition parameters to make sure passing is ok.

and minimized files are use CMD to compress, can assume files are correct

**Comment by ghost** [comment]
> double-check transition parameters to make sure passing is ok.

I've double checked the params, passing will be ok.

**Comment by ChiuWeiYi** [comment]
> > double-check transition parameters to make sure passing is ok.
> 
> I've double checked the params, passing will be ok.

hahaha I forget past tense
I mean I checked in my review, too. :P

**Pull request merged**
